### ISSUE TITLE
Use official plex image

### ISSUE THREAD

**Issue by IAmRGroot** [IAmRGroot/mass#13]
```yaml
plexms:
container_name: plexms
restart: always
image: plexinc/pms-docker
volumes:
  - ${USERDIR}/docker/plexms:/config
  - /data/downloads/plex_tmp:/transcode
  - /data/media:/media
  - ${USERDIR}/docker/shared:/shared
  - /dev/dri:/dev/dri
ports:
  - "32400:32400/tcp"
  - "3005:3005/tcp"
  - "8324:8324/tcp"
  - "32469:32469/tcp"
  - "1900:1900/udp"
  - "32410:32410/udp"
  - "32412:32412/udp"
  - "32413:32413/udp"
  - "32414:32414/udp"
environment:
  - TZ=${TZ}
  - HOSTNAME=""
  - PLEX_CLAIM=""
  - PLEX_UID=${PUID}
  - PLEX_GID=${PGID}
  - ADVERTISE_IP=""
```
